import { generateSKU } from './utils';

export const seedProducts = [
  // Retail Products (10)
  {
    name: 'Nike Air Max 270',
    description: 'The Nike Air Max 270 delivers visible cushioning under every step. The design draws inspiration from the Air Max 93 and Air Max 180, featuring Nike\'s largest heel Air unit yet for a super-soft ride that feels as impossible as it looks.',
    shortDescription: 'Iconic Nike sneakers with maximum Air cushioning for all-day comfort.',
    price: 8500,
    compareAtPrice: 10000,
    category: 'sneakers',
    subcategory: 'running',
    brand: 'Nike',
    sku: generateSKU('Nike Air Max 270', 'sneakers'),
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
    ],
    sizes: [
      { size: '40', stock: 15 },
      { size: '41', stock: 20 },
      { size: '42', stock: 25 },
      { size: '43', stock: 18 },
      { size: '44', stock: 12 },
      { size: '45', stock: 8 },
    ],
    colors: [
      { name: 'Black/White', hex: '#000000', images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800'] },
      { name: 'Red/Black', hex: '#DC2626', images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800'] },
    ],
    tags: ['nike', 'air max', 'running', 'casual', 'comfort'],
    featured: true,
    status: 'active',
    seoTitle: 'Nike Air Max 270 - Premium Running Sneakers | BTT Shoes',
    seoDescription: 'Shop Nike Air Max 270 sneakers with maximum Air cushioning. Free delivery in Nairobi. Authentic Nike shoes at BTT Shoes Kenya.',
    seoKeywords: ['nike air max 270', 'running shoes', 'sneakers kenya', 'nike shoes nairobi'],
    wholesaleTiers: [
      { minQty: 10, price: 7500 },
      { minQty: 50, price: 7000 },
      { minQty: 100, price: 6500 },
    ],
    weight: 0.8,
    dimensions: { length: 32, width: 20, height: 12 },
  },
  {
    name: 'Adidas Ultraboost 22',
    description: 'Experience energy return like never before. These running shoes feature responsive BOOST midsole cushioning and a Primeknit upper that adapts to your foot for a supportive fit.',
    shortDescription: 'Premium Adidas running shoes with BOOST technology for ultimate energy return.',
    price: 12000,
    category: 'sneakers',
    subcategory: 'running',
    brand: 'Adidas',
    sku: generateSKU('Adidas Ultraboost 22', 'sneakers'),
    images: [
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800',
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800',
    ],
    sizes: [
      { size: '39', stock: 10 },
      { size: '40', stock: 18 },
      { size: '41', stock: 22 },
      { size: '42', stock: 20 },
      { size: '43', stock: 15 },
      { size: '44', stock: 10 },
    ],
    colors: [
      { name: 'Core Black', hex: '#000000', images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800'] },
      { name: 'Cloud White', hex: '#FFFFFF', images: ['https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800'] },
    ],
    tags: ['adidas', 'ultraboost', 'running', 'boost', 'primeknit'],
    featured: true,
    status: 'active',
    seoTitle: 'Adidas Ultraboost 22 - BOOST Running Shoes | BTT Shoes',
    seoDescription: 'Shop Adidas Ultraboost 22 with responsive BOOST cushioning. Premium running shoes with Primeknit upper. Free delivery in Nairobi.',
    seoKeywords: ['adidas ultraboost', 'boost running shoes', 'adidas kenya', 'running shoes nairobi'],
    wholesaleTiers: [
      { minQty: 10, price: 10500 },
      { minQty: 50, price: 10000 },
      { minQty: 100, price: 9500 },
    ],
    weight: 0.9,
    dimensions: { length: 33, width: 21, height: 13 },
  },
  {
    name: 'Clarks Desert Boot',
    description: 'The original desert boot. Made from premium suede with a crepe sole, this iconic boot has been a style staple since 1950. Perfect for both casual and smart-casual occasions.',
    shortDescription: 'Classic Clarks desert boots in premium suede with crepe sole.',
    price: 6500,
    category: 'boots',
    subcategory: 'casual',
    brand: 'Clarks',
    sku: generateSKU('Clarks Desert Boot', 'boots'),
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
      'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800',
    ],
    sizes: [
      { size: '40', stock: 12 },
      { size: '41', stock: 15 },
      { size: '42', stock: 18 },
      { size: '43', stock: 14 },
      { size: '44', stock: 10 },
      { size: '45', stock: 6 },
    ],
    colors: [
      { name: 'Sand Suede', hex: '#D2B48C', images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800'] },
      { name: 'Beeswax Leather', hex: '#8B4513', images: ['https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800'] },
    ],
    tags: ['clarks', 'desert boot', 'suede', 'casual', 'classic'],
    featured: true,
    status: 'active',
    seoTitle: 'Clarks Desert Boot - Classic Suede Boots | BTT Shoes',
    seoDescription: 'Shop authentic Clarks Desert Boots in premium suede. The original desert boot since 1950. Free delivery in Nairobi.',
    seoKeywords: ['clarks desert boot', 'suede boots', 'clarks kenya', 'casual boots nairobi'],
    wholesaleTiers: [
      { minQty: 10, price: 5800 },
      { minQty: 50, price: 5500 },
      { minQty: 100, price: 5200 },
    ],
    weight: 1.2,
    dimensions: { length: 30, width: 18, height: 15 },
  },
  {
    name: 'Converse Chuck Taylor All Star',
    description: 'The classic canvas sneaker that started it all. Featuring the iconic silhouette, star logo, and rubber toe cap that have made Chuck Taylor All Stars a timeless favorite.',
    shortDescription: 'Iconic Converse canvas sneakers with classic All Star design.',
    price: 4500,
    category: 'sneakers',
    subcategory: 'casual',
    brand: 'Converse',
    sku: generateSKU('Converse Chuck Taylor', 'sneakers'),
    images: [
      'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=800',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800',
    ],
    sizes: [
      { size: '38', stock: 20 },
      { size: '39', stock: 25 },
      { size: '40', stock: 30 },
      { size: '41', stock: 28 },
      { size: '42', stock: 22 },
      { size: '43', stock: 18 },
      { size: '44', stock: 12 },
    ],
    colors: [
      { name: 'Classic Red', hex: '#DC2626', images: ['https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=800'] },
      { name: 'Black', hex: '#000000', images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800'] },
    ],
    tags: ['converse', 'chuck taylor', 'canvas', 'casual', 'classic'],
    featured: true,
    status: 'active',
    seoTitle: 'Converse Chuck Taylor All Star - Classic Canvas Sneakers | BTT Shoes',
    seoDescription: 'Shop authentic Converse Chuck Taylor All Star sneakers. Classic canvas design with iconic star logo. Free delivery in Nairobi.',
    seoKeywords: ['converse chuck taylor', 'canvas sneakers', 'converse kenya', 'casual shoes nairobi'],
    wholesaleTiers: [
      { minQty: 10, price: 4000 },
      { minQty: 50, price: 3800 },
      { minQty: 100, price: 3500 },
    ],
    weight: 0.6,
    dimensions: { length: 30, width: 19, height: 10 },
  },
  {
    name: 'Vans Old Skool',
    description: 'The classic skate shoe with the iconic side stripe. Features durable canvas and suede uppers, reinforced toe caps, and the signature waffle outsole for superior grip.',
    shortDescription: 'Classic Vans skate shoes with iconic side stripe and waffle sole.',
    price: 5200,
    category: 'sneakers',
    subcategory: 'skate',
    brand: 'Vans',
    sku: generateSKU('Vans Old Skool', 'sneakers'),
    images: [
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800',
      'https://images.unsplash.com/photo-1520256862855-398228c41684?w=800',
    ],
    sizes: [
      { size: '39', stock: 15 },
      { size: '40', stock: 20 },
      { size: '41', stock: 25 },
      { size: '42', stock: 22 },
      { size: '43', stock: 18 },
      { size: '44', stock: 12 },
    ],
    colors: [
      { name: 'Black/White', hex: '#000000', images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800'] },
      { name: 'Navy/White', hex: '#1E3A8A', images: ['https://images.unsplash.com/photo-1520256862855-398228c41684?w=800'] },
    ],
    tags: ['vans', 'old skool', 'skate', 'casual', 'waffle sole'],
    featured: false,
    status: 'active',
    seoTitle: 'Vans Old Skool - Classic Skate Shoes | BTT Shoes',
    seoDescription: 'Shop Vans Old Skool skate shoes with iconic side stripe. Durable canvas and suede construction. Free delivery in Nairobi.',
    seoKeywords: ['vans old skool', 'skate shoes', 'vans kenya', 'casual sneakers nairobi'],
    wholesaleTiers: [
      { minQty: 10, price: 4600 },
      { minQty: 50, price: 4300 },
      { minQty: 100, price: 4000 },
    ],
    weight: 0.7,
    dimensions: { length: 31, width: 20, height: 11 },
  },
  {
    name: 'Timberland 6-Inch Premium Boot',
    description: 'The original yellow boot. Crafted with premium nubuck leather, seam-sealed waterproof construction, and padded collar for comfort. Built to last in any weather.',
    shortDescription: 'Premium Timberland waterproof boots with nubuck leather construction.',
    price: 15000,
    category: 'boots',
    subcategory: 'work',
    brand: 'Timberland',
    sku: generateSKU('Timberland 6-Inch Premium', 'boots'),
    images: [
      'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
    ],
    sizes: [
      { size: '40', stock: 8 },
      { size: '41', stock: 12 },
      { size: '42', stock: 15 },
      { size: '43', stock: 12 },
      { size: '44', stock: 10 },
      { size: '45', stock: 6 },
    ],
    colors: [
      { name: 'Wheat Nubuck', hex: '#DEB887', images: ['https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800'] },
      { name: 'Black Nubuck', hex: '#000000', images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800'] },
    ],
    tags: ['timberland', 'premium boot', 'waterproof', 'work boot', 'nubuck'],
    featured: false,
    status: 'active',
    seoTitle: 'Timberland 6-Inch Premium Boot - Waterproof Work Boots | BTT Shoes',
    seoDescription: 'Shop Timberland 6-Inch Premium Boots with waterproof construction. Premium nubuck leather work boots. Free delivery in Nairobi.',
    seoKeywords: ['timberland boots', 'waterproof boots', 'work boots kenya', 'premium boots nairobi'],
    wholesaleTiers: [
      { minQty: 10, price: 13500 },
      { minQty: 50, price: 13000 },
      { minQty: 100, price: 12500 },
    ],
    weight: 1.5,
    dimensions: { length: 32, width: 20, height: 18 },
  },
  {
    name: 'Puma Suede Classic',
    description: 'The legendary Puma Suede that put PUMA on the map. This classic features a soft suede upper, rubber outsole, and the iconic PUMA Formstrip for a timeless look.',
    shortDescription: 'Legendary Puma Suede sneakers with classic formstrip design.',
    price: 4800,
    category: 'sneakers',
    subcategory: 'casual',
    brand: 'Puma',
    sku: generateSKU('Puma Suede Classic', 'sneakers'),
    images: [
      'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800',
    ],
    sizes: [
      { size: '39', stock: 18 },
      { size: '40', stock: 22 },
      { size: '41', stock: 25 },
      { size: '42', stock: 20 },
      { size: '43', stock: 15 },
      { size: '44', stock: 10 },
    ],
    colors: [
      { name: 'Peacoat/White', hex: '#1E3A8A', images: ['https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800'] },
      { name: 'Classic Blue', hex: '#3B82F6', images: ['https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800'] },
    ],
    tags: ['puma', 'suede', 'classic', 'casual', 'formstrip'],
    featured: false,
    status: 'active',
    seoTitle: 'Puma Suede Classic - Legendary Suede Sneakers | BTT Shoes',
    seoDescription: 'Shop Puma Suede Classic sneakers with iconic Formstrip. Legendary suede construction and timeless design. Free delivery in Nairobi.',
    seoKeywords: ['puma suede classic', 'suede sneakers', 'puma kenya', 'casual shoes nairobi'],
    wholesaleTiers: [
      { minQty: 10, price: 4300 },
      { minQty: 50, price: 4000 },
      { minQty: 100, price: 3800 },
    ],
    weight: 0.7,
    dimensions: { length: 30, width: 19, height: 11 },
  },
  {
    name: 'New Balance 574',
    description: 'The most New Balance shoe ever. Featuring ENCAP midsole technology, premium suede and mesh upper, and the classic 574 silhouette that defines retro-modern style.',
    shortDescription: 'Classic New Balance 574 with ENCAP technology and retro styling.',
    price: 7200,
    category: 'sneakers',
    subcategory: 'lifestyle',
    brand: 'New Balance',
    sku: generateSKU('New Balance 574', 'sneakers'),
    images: [
      'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800',
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800',
    ],
    sizes: [
      { size: '40', stock: 16 },
      { size: '41', stock: 20 },
      { size: '42', stock: 24 },
      { size: '43', stock: 18 },
      { size: '44', stock: 12 },
      { size: '45', stock: 8 },
    ],
    colors: [
      { name: 'Grey/Navy', hex: '#6B7280', images: ['https://images.unsplash.com/photo-1539185441755-769473a23570?w=800'] },
      { name: 'Burgundy/Grey', hex: '#7C2D12', images: ['https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800'] },
    ],
    tags: ['new balance', '574', 'encap', 'lifestyle', 'retro'],
    featured: false,
    status: 'active',
    seoTitle: 'New Balance 574 - Classic Lifestyle Sneakers | BTT Shoes',
    seoDescription: 'Shop New Balance 574 sneakers with ENCAP technology. Classic retro-modern design with premium materials. Free delivery in Nairobi.',
    seoKeywords: ['new balance 574', 'lifestyle sneakers', 'new balance kenya', 'retro sneakers nairobi'],
    wholesaleTiers: [
      { minQty: 10, price: 6500 },
      { minQty: 50, price: 6200 },
      { minQty: 100, price: 5900 },
    ],
    weight: 0.8,
    dimensions: { length: 31, width: 20, height: 12 },
  },
  {
    name: 'Dr. Martens 1460',
    description: 'The original Dr. Martens boot. Built to last with smooth leather upper, iconic yellow stitching, air-cushioned sole, and the classic 8-eyelet design.',
    shortDescription: 'Iconic Dr. Martens 1460 boots with air-cushioned sole and yellow stitching.',
    price: 11500,
    category: 'boots',
    subcategory: 'fashion',
    brand: 'Dr. Martens',
    sku: generateSKU('Dr. Martens 1460', 'boots'),
    images: [
      'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
    ],
    sizes: [
      { size: '39', stock: 10 },
      { size: '40', stock: 14 },
      { size: '41', stock: 16 },
      { size: '42', stock: 18 },
      { size: '43', stock: 14 },
      { size: '44', stock: 10 },
      { size: '45', stock: 6 },
    ],
    colors: [
      { name: 'Black Smooth', hex: '#000000', images: ['https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800'] },
      { name: 'Cherry Red', hex: '#DC2626', images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800'] },
    ],
    tags: ['dr martens', '1460', 'air cushioned', 'fashion boot', 'yellow stitching'],
    featured: false,
    status: 'active',
    seoTitle: 'Dr. Martens 1460 - Original Air-Cushioned Boots | BTT Shoes',
    seoDescription: 'Shop Dr. Martens 1460 boots with iconic air-cushioned sole. Original design with yellow stitching. Free delivery in Nairobi.',
    seoKeywords: ['dr martens 1460', 'air cushioned boots', 'dr martens kenya', 'fashion boots nairobi'],
    wholesaleTiers: [
      { minQty: 10, price: 10300 },
      { minQty: 50, price: 9800 },
      { minQty: 100, price: 9300 },
    ],
    weight: 1.4,
    dimensions: { length: 31, width: 19, height: 17 },
  },
  {
    name: 'Reebok Classic Leather',
    description: 'Clean. Simple. Classic. The Reebok Classic Leather features a soft garment leather upper, comfortable terry lining, and a durable rubber outsole.',
    shortDescription: 'Clean and simple Reebok Classic Leather with garment leather upper.',
    price: 5500,
    category: 'sneakers',
    subcategory: 'lifestyle',
    brand: 'Reebok',
    sku: generateSKU('Reebok Classic Leather', 'sneakers'),
    images: [
      'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800',
    ],
    sizes: [
      { size: '39', stock: 14 },
      { size: '40', stock: 18 },
      { size: '41', stock: 22 },
      { size: '42', stock: 20 },
      { size: '43', stock: 16 },
      { size: '44', stock: 12 },
    ],
    colors: [
      { name: 'White/Gum', hex: '#FFFFFF', images: ['https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800'] },
      { name: 'Black/White', hex: '#000000', images: ['https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800'] },
    ],
    tags: ['reebok', 'classic leather', 'lifestyle', 'clean', 'simple'],
    featured: false,
    status: 'active',
    seoTitle: 'Reebok Classic Leather - Clean Lifestyle Sneakers | BTT Shoes',
    seoDescription: 'Shop Reebok Classic Leather sneakers with soft garment leather. Clean and simple design for everyday wear. Free delivery in Nairobi.',
    seoKeywords: ['reebok classic leather', 'lifestyle sneakers', 'reebok kenya', 'classic shoes nairobi'],
    wholesaleTiers: [
      { minQty: 10, price: 4900 },
      { minQty: 50, price: 4600 },
      { minQty: 100, price: 4300 },
    ],
    weight: 0.7,
    dimensions: { length: 30, width: 19, height: 11 },
  },

  // Wholesale-Specific Products (5)
  {
    name: 'BTT Business Oxford - Bulk Pack',
    description: 'Professional oxford shoes designed for corporate environments. Genuine leather construction with cushioned insole and durable rubber sole. Perfect for offices, hotels, and corporate uniforms.',
    shortDescription: 'Professional oxford shoes in genuine leather - ideal for corporate bulk orders.',
    price: 3500,
    category: 'formal',
    subcategory: 'oxford',
    brand: 'BTT',
    sku: generateSKU('BTT Business Oxford', 'formal'),
    images: [
      'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800',
    ],
    sizes: [
      { size: '39', stock: 100 },
      { size: '40', stock: 150 },
      { size: '41', stock: 200 },
      { size: '42', stock: 180 },
      { size: '43', stock: 120 },
      { size: '44', stock: 80 },
      { size: '45', stock: 50 },
    ],
    colors: [
      { name: 'Black Leather', hex: '#000000', images: ['https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800'] },
      { name: 'Brown Leather', hex: '#8B4513', images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800'] },
    ],
    tags: ['oxford', 'formal', 'business', 'corporate', 'bulk', 'wholesale'],
    featured: false,
    status: 'active',
    seoTitle: 'BTT Business Oxford Shoes - Corporate Bulk Orders | BTT Shoes',
    seoDescription: 'Professional oxford shoes for corporate bulk orders. Genuine leather construction with volume discounts. Perfect for offices and hotels.',
    seoKeywords: ['oxford shoes bulk', 'corporate shoes kenya', 'business shoes wholesale', 'formal shoes nairobi'],
    wholesaleTiers: [
      { minQty: 20, price: 3000 },
      { minQty: 50, price: 2800 },
      { minQty: 100, price: 2500 },
      { minQty: 500, price: 2200 },
    ],
    weight: 1.0,
    dimensions: { length: 30, width: 18, height: 12 },
  },
  {
    name: 'BTT School Uniform Shoes - Student Pack',
    description: 'Durable school shoes designed for daily wear. Black leather upper with reinforced toe and heel, non-slip sole, and comfortable padding. Meets school uniform requirements.',
    shortDescription: 'Durable black school shoes with reinforced construction for students.',
    price: 2200,
    category: 'school',
    subcategory: 'uniform',
    brand: 'BTT',
    sku: generateSKU('BTT School Uniform', 'school'),
    images: [
      'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800',
    ],
    sizes: [
      { size: '32', stock: 80 },
      { size: '33', stock: 100 },
      { size: '34', stock: 120 },
      { size: '35', stock: 150 },
      { size: '36', stock: 180 },
      { size: '37', stock: 200 },
      { size: '38', stock: 150 },
      { size: '39', stock: 120 },
      { size: '40', stock: 100 },
    ],
    colors: [
      { name: 'Black', hex: '#000000', images: ['https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800'] },
    ],
    tags: ['school shoes', 'uniform', 'student', 'durable', 'bulk', 'wholesale'],
    featured: false,
    status: 'active',
    seoTitle: 'BTT School Uniform Shoes - Student Bulk Orders | BTT Shoes',
    seoDescription: 'Durable school uniform shoes for bulk orders. Black leather construction with reinforced design. Perfect for schools and institutions.',
    seoKeywords: ['school shoes bulk', 'uniform shoes kenya', 'student shoes wholesale', 'school shoes nairobi'],
    wholesaleTiers: [
      { minQty: 50, price: 1900 },
      { minQty: 100, price: 1700 },
      { minQty: 200, price: 1500 },
      { minQty: 500, price: 1300 },
    ],
    weight: 0.8,
    dimensions: { length: 28, width: 17, height: 10 },
  },
  {
    name: 'BTT Safety Work Boots - Industrial Pack',
    description: 'Heavy-duty safety boots with steel toe cap, puncture-resistant sole, and oil-resistant rubber outsole. Meets industrial safety standards for construction and manufacturing.',
    shortDescription: 'Industrial safety boots with steel toe and puncture-resistant sole.',
    price: 4500,
    category: 'safety',
    subcategory: 'industrial',
    brand: 'BTT',
    sku: generateSKU('BTT Safety Work Boots', 'safety'),
    images: [
      'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
    ],
    sizes: [
      { size: '40', stock: 60 },
      { size: '41', stock: 80 },
      { size: '42', stock: 100 },
      { size: '43', stock: 90 },
      { size: '44', stock: 70 },
      { size: '45', stock: 50 },
      { size: '46', stock: 30 },
    ],
    colors: [
      { name: 'Black Leather', hex: '#000000', images: ['https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=800'] },
      { name: 'Brown Leather', hex: '#8B4513', images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800'] },
    ],
    tags: ['safety boots', 'steel toe', 'industrial', 'work boots', 'bulk', 'wholesale'],
    featured: false,
    status: 'active',
    seoTitle: 'BTT Safety Work Boots - Industrial Bulk Orders | BTT Shoes',
    seoDescription: 'Industrial safety boots with steel toe cap for bulk orders. Puncture-resistant and oil-resistant. Perfect for construction companies.',
    seoKeywords: ['safety boots bulk', 'steel toe boots kenya', 'industrial boots wholesale', 'work boots nairobi'],
    wholesaleTiers: [
      { minQty: 20, price: 4000 },
      { minQty: 50, price: 3700 },
      { minQty: 100, price: 3400 },
      { minQty: 200, price: 3100 },
    ],
    weight: 1.8,
    dimensions: { length: 32, width: 20, height: 18 },
  },
  {
    name: 'BTT Hotel Slip-On - Hospitality Pack',
    description: 'Professional slip-on shoes designed for hospitality industry. Non-slip sole, comfortable cushioning, and easy-to-clean synthetic leather. Perfect for hotels, restaurants, and service staff.',
    shortDescription: 'Professional slip-on shoes with non-slip sole for hospitality staff.',
    price: 2800,
    category: 'hospitality',
    subcategory: 'service',
    brand: 'BTT',
    sku: generateSKU('BTT Hotel Slip-On', 'hospitality'),
    images: [
      'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800',
    ],
    sizes: [
      { size: '37', stock: 80 },
      { size: '38', stock: 100 },
      { size: '39', stock: 120 },
      { size: '40', stock: 150 },
      { size: '41', stock: 140 },
      { size: '42', stock: 120 },
      { size: '43', stock: 100 },
      { size: '44', stock: 80 },
    ],
    colors: [
      { name: 'Black', hex: '#000000', images: ['https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800'] },
      { name: 'White', hex: '#FFFFFF', images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800'] },
    ],
    tags: ['slip-on', 'hospitality', 'non-slip', 'service', 'bulk', 'wholesale'],
    featured: false,
    status: 'active',
    seoTitle: 'BTT Hotel Slip-On Shoes - Hospitality Bulk Orders | BTT Shoes',
    seoDescription: 'Professional slip-on shoes for hospitality bulk orders. Non-slip sole and easy-to-clean design. Perfect for hotels and restaurants.',
    seoKeywords: ['hospitality shoes bulk', 'slip-on shoes kenya', 'hotel shoes wholesale', 'service shoes nairobi'],
    wholesaleTiers: [
      { minQty: 30, price: 2400 },
      { minQty: 50, price: 2200 },
      { minQty: 100, price: 2000 },
      { minQty: 300, price: 1800 },
    ],
    weight: 0.6,
    dimensions: { length: 29, width: 18, height: 8 },
  },
  {
    name: 'BTT Sports Training Shoes - Team Pack',
    description: 'Versatile training shoes for sports teams and fitness centers. Breathable mesh upper, cushioned midsole, and durable rubber outsole. Suitable for multiple sports activities.',
    shortDescription: 'Versatile training shoes with breathable mesh for sports teams.',
    price: 3200,
    category: 'sports',
    subcategory: 'training',
    brand: 'BTT',
    sku: generateSKU('BTT Sports Training', 'sports'),
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800',
    ],
    sizes: [
      { size: '38', stock: 70 },
      { size: '39', stock: 90 },
      { size: '40', stock: 110 },
      { size: '41', stock: 130 },
      { size: '42', stock: 120 },
      { size: '43', stock: 100 },
      { size: '44', stock: 80 },
      { size: '45', stock: 60 },
    ],
    colors: [
      { name: 'White/Blue', hex: '#3B82F6', images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800'] },
      { name: 'Black/Red', hex: '#DC2626', images: ['https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800'] },
    ],
    tags: ['training shoes', 'sports', 'team', 'fitness', 'bulk', 'wholesale'],
    featured: false,
    status: 'active',
    seoTitle: 'BTT Sports Training Shoes - Team Bulk Orders | BTT Shoes',
    seoDescription: 'Versatile training shoes for sports teams bulk orders. Breathable mesh and cushioned design. Perfect for schools and sports clubs.',
    seoKeywords: ['sports shoes bulk', 'training shoes kenya', 'team shoes wholesale', 'fitness shoes nairobi'],
    wholesaleTiers: [
      { minQty: 25, price: 2800 },
      { minQty: 50, price: 2600 },
      { minQty: 100, price: 2400 },
      { minQty: 200, price: 2200 },
    ],
    weight: 0.9,
    dimensions: { length: 31, width: 20, height: 12 },
  },
];

